apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ .Values.filestore.pvName | quote }}
spec:
  storageClassName: ""
  capacity:
    storage: "1Ti"
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
  csi:
    driver: filestore.csi.storage.gke.io
    # We use 'printf' here to build the volumeHandle string cleanly
    volumeHandle: {{ printf "modeInstance/%s/%s/%s" .Values.filestore.location .Values.filestore.instanceName .Values.filestore.shareName | quote }}
    volumeAttributes:
      ip: {{ .Values.filestore.ipAddress | quote }}
      volume: {{ .Values.filestore.shareName | quote }}
  claimRef:
    # The claimRef MUST point to the namespace where the PVC will be created
    name: {{ .Values.filestore.pvcName | quote }}
    namespace: {{ .Release.Namespace | quote }}
---
kind: PersistentVolumeClaim 
apiVersion: v1
metadata:
  name: {{ .Values.filestore.pvcName | quote }}
  namespace: {{ .Release.Namespace | quote }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  volumeName: {{ .Values.filestore.pvName | quote }}
  resources:
    requests:
      storage: {{ .Values.filestore.capacity | quote }}